name: dr_nashar
description: application for Dr Nashar courses

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_windowmanager: ^0.2.0
  video_player: ^2.5.1
  chewie: ^1.3.6
  firebase_storage: ^11.0.10
  file_picker: ^5.2.5
  dio: ^4.0.6
  flutter_native_splash: ^2.2.16
  rive: ^0.10.2
  provider: ^6.0.3
  import_sorter: ^4.6.0
  fluttertoast: ^8.1.3
  cloud_firestore: ^4.4.0
  liquid_progress_indicator: ^0.4.0
  shared_preferences: ^2.0.17
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  webview_flutter: ^4.0.4
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.11.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Icon/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "images/Icon/Icon.png"
  adaptive_icon_background: "#000000"
flutter_native_splash:
  color: "#000000"
  image: images/Icon/Icon.png


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/Icon/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
