name: dr_nashar
description: application for Dr Nashar courses

publish_to: "none"

version: 1.0.4+9

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  chewie: ^1.4.0
  cloud_firestore: ^4.4.4
  conditional_builder_rec: ^1.0.0
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  dio: ^5.0.1
  dotted_border: ^2.0.0+3
  equatable:
  file_picker: ^5.2.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_downloader: ^1.10.2
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_native_splash: ^2.2.16
  flutter_spinkit: ^5.1.0
  flutter_vector_icons: ^2.0.0
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.2.1
  import_sorter: ^4.6.0
  intl: ^0.17.0
  liquid_progress_indicator: ^0.4.0
  open_file_plus: ^3.4.0
  path_provider: ^2.0.13
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  rive: ^0.10.2
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  step_progress_indicator: ^1.0.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.10
  video_player: ^2.5.3
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/Icon/appIcon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: "images/Icon/Icon.png"
  adaptive_icon_background: "#000000"

flutter_native_splash:
  color: "#000000"
  image: "images/Icon/Icon.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - images/
    - images/Icon/
    - assets/translations/
